sonar.projectKey=celdexia

# Nombre legible que verás en la interfaz
sonar.projectName=celdexia

# Versión del proyecto
sonar.projectVersion=1.0

# Carpeta que contiene el código fuente (. indica la carpeta actual)
sonar.sources=.

# Codificación de los archivos
sonar.sourceEncoding=UTF-8

# (Opcional) Excluir librerías o dependencias para que no ensucien el análisis
sonar.exclusions=**/node_modules/**, **/dist/**, **/vendor/**